In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array ([1,2,3,4,5,6])

print (arr)

[1 2 3 4 5 6]


In [5]:
#0-D array
arr = np.array (42)

print (arr)

42


In [7]:
#2-D arrays
arr = np.array([[1,2,3], [4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
#3-D arrays
arr = np.array ([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
#Dimensions
a = np.array(42)
b= np.array([1,2,3,4,5])
c= np.array([[1,2,3], [4,5,6]])
d= np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [10]:
print(a.dtype)

int32


In [11]:
arr = np.array ([1,2,3])
for x in arr:
    print(x)

1
2
3


In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print (x)

[1 2 3]
[4 5 6]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [14]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print (x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [15]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [16]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print (x)

1
2
3
4
5
6
7
8


In [17]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags = ['buffered'], op_dtypes = ['S']):
    print(x)

b'1'
b'2'
b'3'


In [18]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

arr = np.concatenate((a, b))

print(arr)

[1 2 3 4 5 6]


In [19]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6], [7, 8]])

arr = np.concatenate((a, b), axis = 1)

print (arr)

[[1 2 5 6]
 [3 4 7 8]]


In [21]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6], [7, 8]])

arr = np.concatenate((a, b), axis = 0)

print (arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [22]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6], [7, 8]])

arr = np.stack((a, b), axis = 1)

print (arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [23]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6], [7, 8]])

arr = np.stack((a, b), axis = 0)

print (arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

arr = np.hstack((a, b))

print(arr)

[1 2 3 4 5 6]


In [25]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

arr = np.vstack((a, b))

print(arr)

[[1 2 3]
 [4 5 6]]


In [26]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

arr = np.dstack((a, b))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [30]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis = 1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [34]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [37]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [38]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side = 'right')

print(x)

2


In [39]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [40]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [41]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [42]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [43]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [44]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]
